#!/bin/sh

set -e

lb config noauto \
    -a amd64 \
    -k amd64 \
    --distribution wheezy \
    --archive-areas "main contrib non-free" \
    --checksums sha256 \
    --debian-installer true \
    --firmware-chroot true \
    --firmware-binary true \
    --bootappend-live "boot=live config locales=hu_HU.UTF-8 keyboard-layouts=hu" \
	"${@}"
